from datetime import datetime
from typing import Optional, List
from pydantic import BaseModel, ConfigDict, Field

class TicketBase(BaseModel):
    system_id: Optional[str] = Field("PRD", description="SAP System ID (e.g. PRD, DEV, QAS)")
    client: Optional[str] = Field("100", description="SAP Mandant/Client number")
    component: Optional[str] = Field("GENERAL", description="SAP Module/Component (e.g., SD-BF, MM-PUR, FI-CO, BASIS)")
    tcode: Optional[str] = Field(None, description="SAP Transaction Code (e.g. VA01, ME21N, ST22)")
    category: Optional[str] = Field("Incident", description="Incident classification")
    priority: Optional[str] = Field("3-Medium", description="SAP Severity level (1-Very High, 2-High, 3-Medium, 4-Low)")
    
    customer_name: str = Field(..., description="Customer / Reporter Name")
    customer_email: str = Field(..., description="Customer Email Address")
    company_name: Optional[str] = Field(None, description="Customer Organization Name")
    
    subject: Optional[str] = Field(None, description="Email Subject or Brief Incident Title")
    description: str = Field(..., description="Detailed issue description")
    error_code: Optional[str] = Field(None, description="SAP Error Code or ABAP Dump Exception")
    error_message: Optional[str] = Field(None, description="Extracted SAP Error Message")
    attachment_path: Optional[str] = Field(None, description="Saved attachment paths")
    status: Optional[str] = Field("NEW", description="Ticket Lifecycle Status (NEW, IN_PROGRESS, RESOLVED, CLOSED)")

class TicketCreate(TicketBase):
    ticket_id: Optional[str] = Field(None, description="Custom Ticket ID (autogenerated if omitted)")

class TicketResponse(TicketBase):
    id: int
    ticket_id: str
    created_time: datetime
    updated_time: datetime

    model_config = ConfigDict(from_attributes=True)

class ExtractionResult(BaseModel):
    is_sap_incident: bool = True
    relevance_reason: Optional[str] = ""
    customer_name: Optional[str] = ""
    customer_email: Optional[str] = ""
    company_name: Optional[str] = ""
    system_id: Optional[str] = "PRD"
    client: Optional[str] = "100"
    component: Optional[str] = ""
    tcode: Optional[str] = ""
    category: Optional[str] = "Incident"
    priority: Optional[str] = "3-Medium"
    problem_description: Optional[str] = ""
    error_code: Optional[str] = ""
    error_message: Optional[str] = ""
    attachment_details: Optional[str] = ""

class TicketFilter(BaseModel):
    status: Optional[str] = None
    priority: Optional[str] = None
    system_id: Optional[str] = None
    component: Optional[str] = None
    skip: int = 0
    limit: int = 500
